server:
  port: 9192

spring:
  h2:
    console:
      enabled: true
  application:
    name: ORDER-SERVICE
  zipkin:
    base-url: http://localhost:9411/

logging:
  file:
    name: C:/Users/dotac/Desktop/logs/microservice.log